version: '3.1'

services:
  app:
    build: .
    container_name: app
    expose:
      - '8081'
    ports:
      - '8081:8081'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/PostingDb
      - SPRING_DATASOURCE_USERNAME=******
      - SPRING_DATASOURCE_PASSWORD=******

  db:
    image: 'mysql:latest'
    container_name: db
    environment:
      MYSQL_DATABASE: PostingDb
      MYSQL_USER:
      MYSQL_PASSWORD: